### This notebook:
- processes the gun violence database
- gets the corresponding senator info for each state where a shooting happens (although this is messy and incomplete)

### To DO:
- GOAL: a database with incident ID, incident date, stat

### Gun Violence Database

In [39]:
# Imports
import pandas as pd
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen
import re
import csv

### Import the data

In [40]:
# Access the gun violence database
# this is downloadable here: https://www.gunviolencearchive.org/mass-shooting?sort=desc&order=%23%20Killed
later_data = 'gun-violence-database-part-one.csv' 
earlier_data = 'gun-violence-database-part-two.csv'
early_df = pd.read_csv(earlier_data) 
late_df = pd.read_csv(later_data)
df = early_df.append(late_df, ignore_index=True)

### Clean the data

In [41]:
# Cleaning the Gun violence df
df['Incident Date'] =pd.to_datetime(df['Incident Date'], format= '%B %d, %Y') # make the dates from strings to datetime
df = df[['Incident ID', 'Incident Date', 'State', 'City Or County', 'Address',
       '# Killed', '# Injured']] # get rid of the "Operations" column

### Add new variables

In [42]:
# Add a column for the location of the shooting 
df.loc[1710, 'Location Type'] = 'public space' # vegas - public space (concert)
df.loc[12, 'Location Type'] = 'public space' # orlando - club
df.loc[93, 'Location Type'] = 'school' # sandy hook - elementary school
df.loc[1676, 'Location Type'] = 'religious space' # sutherland springs - religious space (church)
df.loc[1059, 'Location Type'] = 'public space' # el paso- public space (Walmart)
df.loc[1610, 'Location Type'] = 'school' # parkland - school (high school)
df.loc[25, 'Location Type'] = 'public space' # San Bernadino - health dept christmas party
df.loc[86, 'Location Type'] = 'public space' # Navy yard - Us military base
df.loc[1156, 'Location Type'] = 'public space' # virginia beach - public space (municipal govt building)
df.loc[1333, 'Location Type'] = 'public space' # thousand oaks - public space (bar)
df.loc[1345, 'Location Type'] = 'religious space' # pittsburgh - religious space (synagogue)
df.loc[28, 'Location Type'] = 'school' # Roseburg - community college
df.loc[1539, 'Location Type'] = 'school' # santa fe - school (high school)
df.loc[172, 'Location Type'] = 'public space' # boulder - public space (supermarket)
df.loc[1058, 'Location Type'] = 'public space' # dayton - public space (bar)
df.loc[128, 'Location Type'] = 'public space'# Indianapolis - public space (FedEx facility)
df.loc[1733, 'Location Type'] = 'private space'# PLano - private space (home)
df.loc[42, 'Location Type'] = 'religious space'# Charleston - religious space (church)
df.loc[44, 'Location Type'] = 'public space'# Waco - shootout in a restaurant 
df.loc[180, 'Location Type'] = 'public space'# Acworth - public space (spa)
df.loc[1023, 'Location Type'] = 'public space' # Odessa - public space (on the street)
df.loc[15, 'Location Type'] = 'private space' # Pike county - several homes
df.loc[47, 'Location Type'] = 'public space' #Tyrone - across town 
df.loc[34, 'Location Type'] = 'private space' # harris county - home 
df.loc[1853, 'Location Type'] = 'private space' # Bogue Chitto - private space (homes)

In [43]:
# Victims Data
# Vegas
df.loc[1710, 'Gender of Killed'] = 36/(36+22) # Women/ total 
# Source: https://en.wikipedia.org/wiki/2017_Las_Vegas_shooting#Fatalities
vegas_victims_ages = [34, 35, 49, 34, 54, 44, 40, 50, 34, 28, 58, 29, 54, 22, 50, 39, 31 ,52, 20 ,40, 34, 44, 42, 38, 34, 33, 42, 55, 23, 28, 28, 29, 67,24, 35, 33, 36, 31, 46, 56, 26, 21, 20, 28,34, 48, 28, 61, 20, 50, 21, 53, 30, 56, 46, 32, 55, 42] 
# Source: https://eu.usatoday.com/story/news/nation/2017/10/06/here-all-victims-las-vegas-shooting/733236001/
df.loc[1710, 'Avg Age of Killed'] = sum(vegas_victims_ages)/ len(vegas_victims_ages)

# Orlando 
df.loc[12, 'Majority racialized victims'] = 1 # https://en.wikipedia.org/wiki/Orlando_nightclub_shooting
orlando_victims_ages = [23, 25, 26, 33, 21, 33, 30, 29, 24, 28, 31, 25, 39,21, 25,  50, 32, 26, 22, 22, 41, 27, 30, 40, 19, 30, 25, 32, 49, 35, 18, 37, 27, 20, 25, 36, 32, 25, 37, 24, 24, 35, 25, 34, 33, 25, 22, 37, 31]
df.loc[12, 'Avg Age of Killed'] = sum(orlando_victims_ages)/ len(orlando_victims_ages)
df.loc[12, 'Gender of Killed'] = 6/ len(orlando_victims_ages)

# Sandy Hook # Source: https://en.wikipedia.org/wiki/Sandy_Hook_Elementary_School_shooting
sandy_victims_ages = [52,29,47,52, 30, 56, 27, 6, 7, 6, 7, 6, 6, 6, 7, 6, 6, 6, 7, 6, 6, 6 ,6, 6, 6, 6, 6]
df.loc[93, 'Avg Age of Killed'] = sum(sandy_victims_ages)/ len(sandy_victims_ages)
# Source: https://edition.cnn.com/2017/12/14/us/sandy-hook-newtown-shooting-victims-profiles/index.html
df.loc[93, 'Majority racialized victims'] = 0
df.loc[93, 'Gender of Killed'] = 18/len(sandy_victims_ages)

# Sutherland Springs shooting
springs_shooting = [14,62,51,51,60,58,36,1,36,77,68,16,56,56,33,64,66,30,5,7,56,71]
df.loc[1676, 'Avg Age of Killed'] = sum(springs_shooting)/len(springs_shooting)
df.loc[1676, 'Majority racialized victims'] = 0 # source: https://www.nbcnews.com/storyline/texas-church-shooting/texas-church-shooting-who-were-victims-sutherland-springs-massacre-n818356
df.loc[1676, 'Gender of Killed']= (10+7)/26

In [44]:
# Shooter details
# Vegas # Source: https://en.wikipedia.org/wiki/Stephen_Paddock
df.loc[1710, 'Shooter Name'] =  'Stephen Paddock'
df.loc[1710, 'Shooter Age'] =  64
df.loc[1710, 'Shooter Race'] =  'White'

df.loc[1710, 'Shooter after the shooting'] =  'Suicide'

# Orlando # Source: https://en.wikipedia.org/wiki/Omar_Mateen
df.loc[12, 'Shooter Name'] = 'Omar Mateen'
df.loc[12, 'Shooter Age'] = 29
df.loc[12, 'Shooter Race'] = 'Aghani-American'
df.loc[12, 'Shooter after the shooting'] = 'killed by police'

# Sandy Hook 
df.loc[93, 'Shooter Name'] = 'Adam Lanza'
df.loc[93, 'Shooter Age'] = 20
df.loc[93, 'Shooter Race']= 'White'
df.loc[93, 'Shooter after the shooting']  =  'Suicide'

# Sutherland Springs 
df.loc[1676, 'Shooter Name']= 'Devin Patrick Kelley'
df.loc[1676, 'Shooter Age'] =26
df.loc[1676, 'Shooter Race'] = 'White'
df.loc[1676, 'Shooter after the shooting'] = 'Suicide' # although this is a little foggy

# El paso
df.loc[1059, 'Shooter Name']= 'Patrick Wood Crusius'
df.loc[1059, 'Shooter Age']= 21
df.loc[1059, 'Shooter Race']= 'White'
df.loc[1059, 'Shooter after the shooting']= 'Arrested'

### View subset of shootings with more than 7 deaths

In [45]:
killed_subset = df[df['# Killed']>7]
# killed_subset.sort_values(by=['# Killed'],ascending=False)

### Generate random sample of 10 shootings with more than 7 deaths

In [46]:
import random
ids = []
for incident_id in killed_subset['Incident ID']:
    ids.append(incident_id)

random_indexes = random.sample(ids, 10)
print(random_indexes)

[480366, 853756, 298122, 1410442, 1049217, 1958652, 1249561, 1954379, 577157, 930569]

### Write a csv file with the data from the 10 sampled shootings
Don't need to run this again: it's an out of date version of the data

In [47]:
# the shooting titles correspond to the 'City Or County' column in the df for the randomly sampled shooting ids
shooting_titles = ['Las Vegas','Odessa','Plano','San Bernardino','Boulder','Bogue Chitto','Washington Navy Yard','Houston','Pittsburgh','Virginia Beach'] 

with open('sampled_shootings.csv', 'w', newline='', encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(killed_subset.columns)
    for index, row in killed_subset.iterrows():
        if killed_subset.loc[index, "City Or County"] in shooting_titles:
#             our_sample_df.append(killed_subset.loc[index])
            writer.writerow(killed_subset.loc[index])

### Update the dataset with more information

In [48]:
# Importing the second version to work on it again after already creating it 
v2_df = pd.read_csv('sampled_shootings.csv')

In [49]:
# San Bern 
# Source: https://en.wikipedia.org/wiki/2015_San_Bernardino_attack
sanbern_shooting = [40,60,46,46,27,50,26,45,42,58,31,52,27,37]
v2_df.loc[0, 'Avg Age of Killed'] = sum(sanbern_shooting)/len(sanbern_shooting)
v2_df.loc[0, 'Majority racialized victims'] = 0 
v2_df.loc[0, 'Gender of Killed']= (5)/len(sanbern_shooting)
v2_df.loc[0, 'Shooter Name']= 'Rizwan Farook and Tashfeen Malik'
v2_df.loc[0, 'Shooter Age']= 28 # and 27
v2_df.loc[0, 'Shooter Race']= 'pakistani'
v2_df.loc[0, 'Shooter after the shooting']= 'killed by police'

# Houston
# Source: https://en.wikipedia.org/wiki/2015_Harris_County_shooting#Victims
houston_shooting = [40,50,13,11,10,9,7,6]
v2_df.loc[1, 'Avg Age of Killed'] = sum(houston_shooting)/len(houston_shooting)
v2_df.loc[1, 'Majority racialized victims'] = 1 
v2_df.loc[1, 'Gender of Killed']= 2/len(houston_shooting)
v2_df.loc[1, 'Shooter Name']= 'David Ray Conley'
v2_df.loc[1, 'Shooter Age']= 48
v2_df.loc[1, 'Shooter Race']= 'black' #https://www.chron.com/news/slideshow/8-killed-in-shooting-on-Falling-Oaks-Road-in-NW-114908.php
v2_df.loc[1, 'Shooter after the shooting']= 'arrested by police'

# DC
# Source: https://en.wikipedia.org/wiki/Washington_Navy_Yard_shooting
dc_shooting = [59,53,62,73,50,46,61]
v2_df.loc[2, 'Avg Age of Killed'] = sum(dc_shooting)/len(dc_shooting) # https://www.nytimes.com/2013/09/17/us/shooting-reported-at-washington-navy-yard.html
v2_df.loc[2, 'Majority racialized victims'] = 0 
v2_df.loc[2, 'Gender of Killed']= 2/len(dc_shooting)
v2_df.loc[2, 'Shooter Name']= 'Aaron Alexis'
v2_df.loc[2, 'Shooter Age']= 34
v2_df.loc[2, 'Shooter Race']= 'black' 
v2_df.loc[2, 'Shooter after the shooting']= 'killed by police'

# Boulder
# Source: https://en.wikipedia.org/wiki/2021_Boulder_shooting
boulder_shooting = [49,59,51,61,62,25,23,20,51,65] # https://edition.cnn.com/2021/03/24/us/victims-of-boulder-shooting-wednesday/index.html
v2_df.loc[3, 'Avg Age of Killed'] = sum(boulder_shooting)/len(boulder_shooting)
v2_df.loc[3, 'Majority racialized victims'] = 0 
v2_df.loc[3, 'Gender of Killed']= 6/len(boulder_shooting)
v2_df.loc[3, 'Shooter Name']= 'Ahmad Al Aliwi Al-Issa'
v2_df.loc[3, 'Shooter Age']= 21
v2_df.loc[3, 'Shooter Race']= 'syrian-american' 
v2_df.loc[3, 'Shooter after the shooting']= 'arrested by police'

# Odessa
# Source: https://www.kcbd.com/2019/09/02/victims-odessa-mass-shooting/
odessa_shooting = [29,25,15,40,50,30,34] # https://edition.cnn.com/2021/03/24/us/victims-of-boulder-shooting-wednesday/index.html
v2_df.loc[4, 'Avg Age of Killed'] = sum(odessa_shooting)/len(odessa_shooting)
v2_df.loc[4, 'Majority racialized victims'] =  1
v2_df.loc[4, 'Gender of Killed']= (1+1)/len(odessa_shooting)
v2_df.loc[4, 'Shooter Name']= 'Seth Aaron Ator'
v2_df.loc[4, 'Shooter Age']= 36
v2_df.loc[4, 'Shooter Race']= 'white' 
v2_df.loc[4, 'Shooter after the shooting']= 'killed by police'

# Virginia Beach 
# source: https://en.wikipedia.org/wiki/2019_Virginia_Beach_shooting
# ages source:https://www.washingtonpost.com/graphics/2019/local/virginia-beach-shooting-victims/
virginia_shooting = [50,35,65,35,52,60,65,35,65,57,35,65] # many of these ages are !!guesses!!
v2_df.loc[5, 'Avg Age of Killed'] = sum(virginia_shooting)/len(virginia_shooting)
v2_df.loc[5, 'Majority racialized victims'] =  0
v2_df.loc[5, 'Gender of Killed']= 5/12
v2_df.loc[5, 'Shooter Name']= 'DeWayne Craddock'
v2_df.loc[5, 'Shooter Age']= 40
v2_df.loc[5, 'Shooter Race']= 'black' 
v2_df.loc[5, 'Shooter after the shooting']= 'killed by police'

# Pittsburgh
# Source: https://en.wikipedia.org/wiki/Pittsburgh_synagogue_shooting
pittsburgh_shooting = [75, 65, 97, 66, 59,54, 84,86, 71, 88, 69] # https://edition.cnn.com/2021/03/24/us/victims-of-boulder-shooting-wednesday/index.html
v2_df.loc[6, 'Avg Age of Killed'] = sum(pittsburgh_shooting)/len(pittsburgh_shooting)
v2_df.loc[6, 'Majority racialized victims'] = 1 # ????
v2_df.loc[6, 'Gender of Killed']= (4)/len(pittsburgh_shooting)
v2_df.loc[6, 'Shooter Name']= 'Robert Gregory Bowers'
v2_df.loc[6, 'Shooter Age']= 46
v2_df.loc[6, 'Shooter Race']= 'white' 
v2_df.loc[6, 'Shooter after the shooting']= 'killed by police'

# Vegas
v2_df.loc[7, 'Majority racialized victims'] = 0 # ???? theres not good data

# PLano 
# Source:  
plano_shooting = [27, 33 ,24, 29, 22, 31, 28, 25] # https://edition.cnn.com/2021/03/24/us/victims-of-boulder-shooting-wednesday/index.html
v2_df.loc[8, 'Avg Age of Killed'] = sum(plano_shooting)/len(plano_shooting)
v2_df.loc[8, 'Majority racialized victims'] = 0
v2_df.loc[8, 'Gender of Killed']= (3)/len(plano_shooting)
v2_df.loc[8, 'Shooter Name']= 'Spencer Hight'
v2_df.loc[8, 'Shooter Age']= 32
v2_df.loc[8, 'Shooter Race']= 'white' 
v2_df.loc[8, 'Shooter after the shooting']= 'killed by police'

# Bogue Chitto 
# Source:  
bogue_shooting = [36,11,18,55,53,35,45,46] # https://edition.cnn.com/2021/03/24/us/victims-of-boulder-shooting-wednesday/index.html
v2_df.loc[9, 'Avg Age of Killed'] = sum(bogue_shooting)/len(bogue_shooting)
v2_df.loc[9, 'Majority racialized victims'] = 1
v2_df.loc[9, 'Gender of Killed']= (4)/len(bogue_shooting)
v2_df.loc[9, 'Shooter Name']= 'Willie Cory Godbolt'
v2_df.loc[9, 'Shooter Age']= 35
v2_df.loc[9, 'Shooter Race']= 'black' 
v2_df.loc[9, 'Shooter after the shooting']= 'arrested by police'

v2_df

,Incident ID,Incident Date,State,City Or County,Address,# Killed,# Injured,Location Type,Gender of Killed,Avg Age of Killed,Majority racialized victims,Shooter Name,Shooter Age,Shooter Race,Shooter after the shooting
0,456893,2015-12-02 00:00:00,California,San Bernardino,1365 South Waterman Ave,16,19,public space,0.357143,41.928571,0.0,Rizwan Farook and Tashfeen Malik,28.0,pakistani,killed by police
1,390526,2015-08-08 00:00:00,Texas,Houston,2211 Falling Oaks,8,0,private space,0.250000,18.250000,1.0,David Ray Conley,48.0,black,arrested by police
2,480366,2013-09-16 00:00:00,District of Columbia,Washington Navy Yard,1336 Isaac Hull Ave,13,3,public space,0.285714,57.714286,0.0,Aaron Alexis,34.0,black,killed by police
3,1958652,2021-03-22 00:00:00,Colorado,Boulder,3600 Table Mesa Dr,10,1,public space,0.600000,46.600000,0.0,Ahmad Al Aliwi Al-Issa,21.0,syrian-american,arrested by police
4,1492441,2019-08-31 00:00:00,Texas,Odessa,8250 TX 191,8,23,public space,0.285714,31.857143,1.0,Seth Aaron Ator,36.0,white,killed by police
5,1410442,2019-05-31 00:00:00,Virginia,Virginia Beach,2405 Courthouse Drive,13,4,public space,0.416667,51.583333,0.0,DeWayne Craddock,40.0,black,killed by police
6,1241819,2018-10-27 00:00:00,Pennsylvania,Pittsburgh,5898 Wilkins Ave,11,7,religious space,0.363636,74.000000,1.0,Robert Gregory Bowers,46.0,white,killed by police
7,946496,2017-10-01 00:00:00,Nevada,Las Vegas,3950 Las Vegas Blvd S,59,441,public space,0.620690,38.379310,0.0,Stephen Paddock,64.0,White,Suicide
8,930569,2017-09-10 00:00:00,Texas,Plano,1712 West Spring Creek Parkway,9,1,private space,0.375000,27.375000,0.0,Spencer Hight,32.0,white,killed by police
9,853756,2017-05-27 00:00:00,Mississippi,Bogue Chitto,2871 Lee Dr,8,1,private space,0.500000,37.375000,1.0,Willie Cory Godbolt,35.0,black,arrested by police

In [50]:
v2_df.to_csv('v2-sampled_shootings.csv',index=False)

### Wikipedia - US Senators

In [6]:
# Get a df of current senators from a wikipedia page
wiki = 'https://en.wikipedia.org/wiki/List_of_current_United_States_senators'

# state, senator, party, assumed_office = [], [] , [],[]
soup = bs(urlopen(wiki), 'html.parser')
senators = soup.find('table', {'class': 'wikitable sortable'})
senators_df=pd.read_html(str(senators))

In [7]:
# Clean up the senators df
senators_df = pd.DataFrame(senators_df[0]) # just a formatting thing
senators_df = senators_df[['State','Senator', 'Party.1','Assumed office']] # Save only the relevant columns

for x in range(len(senators_df['Assumed office'])): # get rid of the footnotes indicators
    split_ = senators_df['Assumed office'][x].split(' ')
    if split_[-1][-1] == ']':
        end_ = split_[-1][:-3]
        fixed = split_[:-1]
        fixed.append(end_)
        senators_df['Assumed office'][x] = ' '.join(fixed)

senators_df['Assumed office'] =pd.to_datetime(senators_df['Assumed office'], format= '%B %d, %Y') # convert dates to datetime
senators_df
senators_df.sort_values(by=['Assumed office'],ascending=True)

         State           Senator        Party.1 Assumed office
88     Vermont     Patrick Leahy     Democratic     1975-01-03
28        Iowa    Chuck Grassley     Republican     1981-01-03
32    Kentucky   Mitch McConnell     Republican     1985-01-03
0      Alabama    Richard Shelby  Republican[2]     1987-01-03
8   California  Dianne Feinstein     Democratic     1992-11-10
..         ...               ...            ...            ...
83   Tennessee      Bill Hagerty     Republican     2021-01-03
99     Wyoming    Cynthia Lummis     Republican     2021-01-03
19     Georgia   Raphael Warnock     Democratic     2021-01-20
18     Georgia        Jon Ossoff     Democratic     2021-01-20
9   California      Alex Padilla     Democratic     2021-01-20

[100 rows x 4 columns]

### Wikipedia - House of Reps

In [8]:
# Get a df of current reps from a wikipedia page
wiki = 'https://en.wikipedia.org/wiki/List_of_current_members_of_the_United_States_House_of_Representatives'

soup = bs(urlopen(wiki), 'html.parser')
reps = soup.find_all('table', {'class': 'wikitable sortable'})[2] # the 3rd table is the relevant one
reps_df=pd.read_html(str(reps))

In [9]:
# Clean up the senators df
reps_df = pd.DataFrame(reps_df[0]) # just a formatting thing
reps_df = reps_df[['District','Member', 'Party.1','Assumed office']] # Save only the relevant columns

for x in range(len(reps_df['Assumed office'])): # get rid of the extra words in the column 
    split_ = reps_df['Assumed office'][x].split(' ')
    if split_[-1][-1] == ')':
        reps_df['Assumed office'][x] = ''.join(split_[0])
    if split_[0].startswith('V'):
        reps_df['Assumed office'][x] = None

reps_df['Assumed office'] =pd.to_datetime(reps_df['Assumed office'], format= '%Y') # convert dates to datetime


for index, row in reps_df.iterrows():
    state = reps_df.loc[index, 'District']
    new_ = re.sub(r"at-large",'', state)
    extra= re.sub(r"\d",'', new_)
    final = extra.replace(u'\xa0', u' ')
    reps_df.loc[index, 'State'] = final[:-1]
    
reps_df.head()

    District           Member     Party.1 Assumed office    State
0  Alabama 1       Jerry Carl  Republican     2021-01-01  Alabama
1  Alabama 2      Barry Moore  Republican     2021-01-01  Alabama
2  Alabama 3      Mike Rogers  Republican     2003-01-01  Alabama
3  Alabama 4  Robert Aderholt  Republican     1997-01-01  Alabama
4  Alabama 5        Mo Brooks  Republican     2011-01-01  Alabama

### Another option - Congresspeople & their Twitter handles

In [10]:
uc_link ='https://ucsd.libguides.com/congress_twitter/senators'

uc_soup = bs(urlopen(uc_link), 'html.parser')

links_with_text = [a['href'] for a in uc_soup.find_all('a', href=True) if a.text]
twitter_handles = [link for link in links_with_text if re.search(r"//twitter", link)]
        
handles = uc_soup.find_all('table', {'class': 'table table-bordered table-striped table-hover table-condensed'})

handles_df_pt1=pd.read_html(str(handles[0]))
handles_df_pt1 = pd.DataFrame(handles_df_pt1[0]) # just a formatting thing
handles_df_pt1.rename(columns = {0:'Senator', 1:'State',2:'Party'}, inplace = True)
handles_df_pt1=handles_df_pt1.drop([0])
handles_df_pt1['Handle link'] = twitter_handles[:54]


handles_df_pt2=pd.read_html(str(handles[1]))
handles_df_pt2 = pd.DataFrame(handles_df_pt2[0]) # just a formatting thing
handles_df_pt2.rename(columns = {0:'Senator', 1:'State',2:'Party'}, inplace = True)
handles_df_pt2=handles_df_pt2.drop([0])
handles_df_pt2['Handle link'] = twitter_handles[54:]

handles_df= handles_df_pt1.append(handles_df_pt2, ignore_index = True)

for index, row in handles_df.iterrows():
    link = handles_df.loc[index, 'Handle link']
    handles_df.loc[index, 'Handle'] = re.sub(r"https:\/\/twitter\.com\/",'', link)

handles_df.head()

,Senator,State,Party,Handle link,Handle
0,"Baldwin, Tammy",WI,D,https://twitter.com/SenatorBaldwin,SenatorBaldwin
1,"Barrasso, John",WY,R,https://twitter.com/SenJohnBarrasso,SenJohnBarrasso
2,"Bennet, Michael",CO,D,https://twitter.com/SenatorBennet,SenatorBennet
3,"Blackburn, Marsha",TN,R,https://twitter.com/MarshaBlackburn,MarshaBlackburn
4,"Blumenthal, Richard",CT,D,https://twitter.com/SenBlumenthal,SenBlumenthal

In [11]:
uc_reps ='https://ucsd.libguides.com/congress_twitter/reps'

uc_reps = bs(urlopen(uc_reps), 'html.parser')

links_with_text = [a['href'] for a in uc_reps.find_all('a', href=True) if a.text]
twitter_handles = [link for link in links_with_text if re.search(r"//twitter", link)]
twitter_handles.insert(73, None)
twitter_handles.insert(149, None)
twitter_handles.insert(371, None)
twitter_handles.insert(408, None)


rep_handles = uc_reps.find_all('table', {'class': 'table table-bordered table-striped table-hover table-condensed'})

previous_table_length = 0
rep_handles_df =pd.DataFrame()
for i in range(len(rep_handles)):
    df = pd.read_html(str(rep_handles[i]))
    df = pd.DataFrame(df[0]) # just a formatting thing
    df.rename(columns = {0:'Representative', 1:'State',2:'Party'}, inplace = True)
    df=df.drop([0])
    
    current_table_length = len(df['Representative']) +previous_table_length
    df['Handle link'] = twitter_handles[previous_table_length:current_table_length]

    previous_table_length = current_table_length

    rep_handles_df= rep_handles_df.append(df, ignore_index = True)

test = 'string'
type_ = type(test)
for index, row in rep_handles_df.iterrows():
    link = rep_handles_df.loc[index, 'Handle link']
    if type(link) == type_:
        rep_handles_df.loc[index, 'Handle'] = re.sub(r"https:\/\/twitter\.com\/",'', link)
    else: rep_handles_df.loc[index, 'Handle'] = None

rep_handles_df

,Representative,State,Party,Handle link,Handle
0,"Adams, Alma",NC,D,https://twitter.com/RepAdams,RepAdams
1,"Aderholt, Robert",AL,R,https://twitter.com/Robert_Aderholt,Robert_Aderholt
2,"Aguilar, Pete",CA,D,https://twitter.com/RepPeteAguilar,RepPeteAguilar
3,"Allen, Rick W.",GA,R,https://twitter.com/RepRickAllen,RepRickAllen
4,"Allred, Colin",TX,D,https://twitter.com/RepColinAllred,RepColinAllred
...,...,...,...,...,...
433,"Womack, Steve",AR,R,https://twitter.com/rep_stevewomack,rep_stevewomack
434,"Wright, Ron",TX,R,https://twitter.com/RepRonWright,RepRonWright
435,"Yarmuth, John",KY,D,https://twitter.com/RepJohnYarmuth,RepJohnYarmuth
436,"Young, Don",AK,R,https://twitter.com/repdonyoung,repdonyoung
437,"Zeldin, Lee",NY,R,https://twitter.com/RepLeeZeldin,RepLeeZeldin

### Merge the Databases

In [12]:
# Merge the two dataframes
# NOTE: This creates duplicates of all the shootings because there are 2 senators for each state
merged = pd.merge(left=senators_df, right=df, left_on='State', right_on='State')
# print(test2)
# merged2 = pd.merge(left=reps_df, right=merged, left_on='State', right_on='State')
# merged2

In [13]:
# get rid of the senators that were not in office when the shooting took place 
for index, row in merged.iterrows():
    if row['Assumed office'] > row['Incident Date']:
        merged.loc[index, 'Senator'] = 'Unknown'
        merged.loc[index, 'Party.1'] = 'Unknown'
        merged.loc[index, 'Assumed office'] = 'Unknown'

merged[merged['Senator'] == 'Unknown']

Empty DataFrame
Columns: [State, Senator, Party.1, Assumed office, Representative, Party, Handle link]
Index: []

In [ ]:
high_deaths = merged[merged['# Killed']>20]
high_deaths.sort_values(by=['# Killed'],ascending=False)